project:
  type: website

website:
  title: "Kevin Mackay, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
execute:
  echo: true         # show code by default
  warning: false
  message: false
